<?php
  if(!defined('NOW')) define('NOW', time());

  //User Groups
  CONST GROUP_ADMIN = 1;
  CONST GROUP_USER = 2;
  CONST GROUP_GUEST = 3;

  CONST VISIBILITY_PUBLIC = 1;
  CONST VISIBILITY_PRIVATE = 0;

  CONST FILTER_NONE = 0;
  CONST FILTER_BORDER = 1;
  CONST FILTER_LOMO = 2;
  CONST FILTER_LENSFLARE = 3;
  CONST FILTER_BLACKNWHITE = 4;
  CONST FILTER_BLUR = 5;

  CONST UPLOAD_BLOB = "BLOB";
  CONST UPLOAD_SOURCE = "SOURCE";
?>